[package]
name = "rpp-impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = { version = "2.0.13", features = ["visit", "full", "extra-traits"] }
rpp-build = { version = "0.1.0", path = "../rpp-build" }
proc-macro2 = "1.0.56"
